---
- name: mongodb install
  hosts: mongodb
  become: yes # sudo access
  tasks:
  - name: install mongodb server
    ansible.builtin.package:
      name: mongodb
      state: present
  
  - name: start mongodb
    ansible.builtin.service:
      name: mongodb
      state: started
      enabled: yes