---
- name: varables play
  hosts: local
  connection: local
  vars:
    COURSE: ansible
    DURATION: 20HR
    TRAINER: DILLESWARARAO
    LOCATION: vizag
  tasks:
  - name: cource names print the screen 
    ansible.builtin.debug:
      msg: "hii hello {{ COURSE }}, course duration {{ DURATION }}, THE TRAINER IS {{ TRAINER }}, THE TRAINER LOCATION {{ LOCATION }}"

  - name: print again course information 
    ansible.builtin.debug:
      msg: " hello {{ COURSE }}, course duration {{ DURATION }}, THE TRAINER IS {{ TRAINER}}, THE TRAINER LOCATION {{ LOCATION }}"
      
