---
- name: understatnd vars preference
  hosts: local
  connection: local
  vars:
    - GREETING: hello from play
  vars_files:
   - course.yml
  vars_prompt:
    - name: GREETING
      prompt: pleace enter the greeeting 
      priavte: false
  tasks:
    - name: print the grreeting 
      vars:
        GREETING: Hello from tasks
      ansible.builtin.debug:
        msg: "{{ GREETING }}"
        