[local]
localhost


[frontend]
172.31.30.1 COURSE=Ansible DURATION=10hr TRAINER=Satyam ansible_user=ec2-user ansible_password=DevOps321
172.31.24.212 COURSE=Ansible DURATION=10hr TRAINER=Satyam ansible_user=ec2-user ansible_password=DevOps321


[local:vars]
COURSE=Ansible
TRAINER=Dille
DURATION=50HR
