[local]
localhost


[frontend]
54.91.79.243
; 13.221.111.248 COURSE=Ansible DURATION=10hr TRAINER=Satyam ansible_user=ec2-user ansible_password=DevOps321
; 18.208.217.121 COURSE=Ansible DURATION=10hr TRAINER=Satyam ansible_user=ec2-user ansible_password=DevOps321


[local:vars]
COURSE=Ansible
TRAINER=Dille
DURATION=50HR
GREETING="Hello from inventory"